In [1]:
# ---
# title: Mathematical Foundations of Graph Theory
# tags: [Math, GraphTheory, LinearAlgebra, SpectralClustering]
# difficulty: Advanced
# ---

# Mathematical Foundations

How do we mathematically find "hidden regimes" in the stock market? We use **Spectral Graph Theory**.

## 1. The Adjacency Matrix ($A$)
A graph $G = (V, E)$ can be represented as a matrix $A$ where $A_{ij}$ is the weight of the edge between node $i$ and $j$.

In our case, $A_{ij} = |\text{Correlation}(i, j)|$.

## 2. The Laplacian Matrix ($L$)
The Laplacian captures the discrete "energy" of the graph.
$$ L = D - A $$
Where $D$ is the Degree Matrix (diagonal matrix of row sums).

Let's compute this manually on our graph.

In [2]:
import sys
import os
import numpy as np
import networkx as nx
sys.path.append(os.path.abspath("../src"))

from analytics.math_core import MathCore

# Load the real graph
mc = MathCore(gold_path="../data/gold")
G = mc.load_graph()
print(f"Loaded Graph: {G.number_of_nodes()} nodes")

# Let's visualize the Adjacency Matrix
A = nx.to_numpy_array(G)
print("\nAdjacency Matrix A:")
print(np.round(A, 2))

Loading graph from: ../data/gold/market_graph_20251213_005243.gexf
Loaded Graph: 6 nodes

Adjacency Matrix A:
[[0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1.]
 [1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 0.]]


## 3. Spectral Clustering (Eigenvalues)
We calculate the eigenvalues $\lambda$ and eigenvectors $v$ of the Normalized Laplacian.
The eigenvectors corresponding to the smallest non-zero eigenvalues ('Fiedler Vectors') give us the optimal cuts to separate the graph into clusters.

In [3]:
# Run the full clustering pipeline
results = mc.spectral_clustering(k=2)
print(results)

Loading graph from: ../data/gold/market_graph_20251213_005243.gexf
Performing Spectral Clustering on 4 companies...
Laplacian Matrix shape: (4, 4)

Spectral Clusters Found:
  Cluster 0: ['GOOGL']
  Cluster 1: ['NVDA', 'MSFT', 'AAPL']
  Ticker  Cluster
0   NVDA        1
1  GOOGL        0
2   MSFT        1
3   AAPL        1
